### ISSUE TITLE
Maintain issue

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/applescript-mode#3]
@tarsius Anyone maintaining this package? I would like to take over maintenance of this package.

**Comment by tarsius** [comment]
Knock yourself out :grinning: 

Applescript? Is that still a thing?

**Comment by jcs090218** [comment]
I guess someone still use it? lol

**Comment by tarsius** [comment]
You don't?

**Comment by jcs090218** [comment]
My work requires me to do this. So, yes? haha

Let me close this issue. :)
